# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


commands:
  hello:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: circleci/golang:1.14.2 # プライマリコンテナです。このなかでジョブコマンドが実行されます
    steps:
      - run: echo "hello world" # 「echo」コマンドを実行します
  tag:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: circleci/golang:1.14.2 # プライマリコンテナです。このなかでジョブコマンドが実行されます
    steps:
      - run: echo "hello hello" # 「echo」コマンドを実行します

workflows:
  test:
    jobs:
      - hello
      - tag:
          filters:
            branches:
              only: master