# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.14.2

commands:
  hello:
    executor: golang
    steps:
      - run:
          name: Hello
          command: |
            echo hello
  tag:
    executor: golang
    steps:
      - run:
          name: Tag a release
          command: |
            echo tag

workflows:
  test:
    jobs:
      - hello
      - tag:
          filters:
            branches:
              only: master