# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  hello:
    docker:
      - image: circleci/golang:1.14.2
    steps:
      - run: echo hello
  tag:
    docker:
      - image: circleci/golang:1.14.2
    steps:
      - checkout
      - run: echo tag

workflows:
  test:
    jobs:
      - hello
      - tag:
          filters:
            branches:
              only: master
